import sublime

QP_COLOR_NONE = sublime.KIND_ID_AMBIGUOUS
QP_COLOR_REDISH = sublime.KIND_ID_COLOR_REDISH
QP_COLOR_ORANGISH = sublime.KIND_ID_COLOR_ORANGISH
QP_COLOR_YELLOWISH = sublime.KIND_ID_COLOR_YELLOWISH
QP_COLOR_GREENISH = sublime.KIND_ID_COLOR_GREENISH
QP_COLOR_CYANISH = sublime.KIND_ID_COLOR_CYANISH
QP_COLOR_BLUISH = sublime.KIND_ID_COLOR_BLUISH
QP_COLOR_PURPLISH = sublime.KIND_ID_COLOR_PURPLISH
QP_COLOR_PINKISH = sublime.KIND_ID_COLOR_PINKISH
QP_COLOR_DARK = sublime.KIND_ID_COLOR_DARK
QP_COLOR_LIGHT = sublime.KIND_ID_COLOR_LIGHT

QP_YES = "✓"
QP_NO = "✗"
QP_ADD = "+"
QP_FORWARD = "❯"
QP_BACK = "❮"
QP_DETAILS = "⋯"
QP_RENAME = "*"
QP_CHMOD = "7"
QP_DOWNLOAD = "⏬"
QP_EDIT = "a"
